### ISSUE TITLE
モーダルの閉じるボタンがこの場所で固定されていてほしい

### ISSUE THREAD

**Issue by Mahito** [ntt-developers/ntt-tech-conference#202]
related #199

**Comment by kaz1104** [comment]
**修正方法 Memo**
PC、SphのいずれもPositionをAbsoluteからFixedに変更して、rightとtopの位置を(100% - ModalのWidthの%)/2に今のPositionのrightとTop分をcalcで計算させてずらすと、今と同じ位置で固定される。はず。(PC側は検証済み)
