### ISSUE TITLE
placeholder.comとかで，解像度よりnow printingとか出しておいたほうがいい

### ISSUE THREAD

**Issue by Mahito** [ntt-developers/ntt-tech-conference#203]
https://via.placeholder.com/600x400?text=now+printing

related #199

**Comment by hanasuke** [comment]
d5d5ab9394b0563291d9bfc1c6eb6197f893e8d1 で @kaz1104 sanが対応してくれていました．
ref #208 
![image](https://user-images.githubusercontent.com/2376843/72656966-867db980-39e2-11ea-896c-23c606ae54dc.png)
