### ISSUE TITLE
Enable CI/CD via Travis CI

### ISSUE THREAD

**Issue by aajisaka** [ntt-developers/ntt-tech-conference#97]

**Comment by aajisaka** [comment]
Ping @kumagi who did great work for ntt tech conf #1.

**Comment by kumagi** [comment]
I'll do. Just a moment!

**Comment by kumagi** [comment]
solved by #106 
pull-request preview on s3 requires some more time. please wait.

**Comment by aajisaka** [comment]
Thanks!
